#!/bin/bash
# Email Backend Configuration for Render

echo "🔧 Setting up Resend email backend on Render..."
echo ""
echo "📋 Required Environment Variables:"
echo ""
echo "AVA_API_RESEND_API_KEY=re_BoWALHTK_NMs4BvU5ZDmpKbGdYw5zW7yK"
echo "AVA_API_RESEND_DOMAIN=resend.dev"
echo ""
echo "🎯 Steps to configure on Render:"
echo ""
echo "1. Go to: https://dashboard.render.com"
echo "2. Select: ava-api-production service"
echo "3. Click: Environment tab"
echo "4. Add variable: AVA_API_RESEND_API_KEY"
echo "   Value: re_BoWALHTK_NMs4BvU5ZDmpKbGdYw5zW7yK"
echo ""
echo "5. Add variable: AVA_API_RESEND_DOMAIN"
echo "   Value: resend.dev"
echo ""
echo "6. Click: Save Changes"
echo "7. Service will auto-redeploy"
echo ""
echo "✅ After deployment, test with:"
echo "   curl -X POST https://ava-api-production.onrender.com/api/v1/analytics/calls/{call_id}/email \\"
echo "        -H 'Authorization: Bearer YOUR_TOKEN'"
echo ""
